### ISSUE TITLE
Crash upon interacting with the cell

### ISSUE THREAD

**Issue by DWX12** [Spectre0987/PirateMod#4]
Using version 0.0.4 I'm getting a crash upon interacting with the cell with an empty hand (might happen with items in hand or off hand too)

https://paste.dimdev.org/orudehiwes.mccrash

Thanks.

**Comment by Spectre0987** [comment]
Should be fixed in 0.0.5

**Comment by DWX12** [comment]
Seems like you have a number of things either removed or hidden such as the cell, which I'm still getting a crash with:

https://paste.dimdev.org/exipuqatet.mccrash

I have gotten the pirate ships to spawn thanks to your additions, but they spawn with cells holding villagers. Seems like the same crash as before.

Thanks again for your hard work on this mod.
